name: Continuous Integration (CI)

on:
  push:
    branches:
      - main
      - 'feature/**'
  pull_request:
    branches:
      - main

jobs:
  qa:
    runs-on:
      ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install QA dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 black

      - name: Run Black (Formatter Check)
        run: black --check .

      - name: Run Flake8 (Linter Check)
        run: flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics


  test:
    needs:
      - qa
    runs-on:
      ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.12"]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install project dependencies and test tools
      run: |
        python -m pip install --upgrade pip
        # Install the project and test runner (modify 'pip install -e .' based on your project structure)
        pip install -e . pytest pytest-mock

    - name: Run Unit Tests with pytest
      run: pytest tests/
